# Generated by Django 4.0.5 on 2022-11-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_editora_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
